# Sphere debug driver for Python.
#
# Runs one script under bdb and talks to Sphere over stdin/stdout, one JSON
# message per line. No dependency beyond the standard library.
# Regenerated by Sphere when missing.
SPHERE_DEBUG_VERSION = 1

import bdb
import io
import json
import linecache
import os
import queue
import sys
import threading
import traceback

_PROTOCOL = sys.__stdout__
_LOCK = threading.RLock()
_commands = queue.Queue()


def _send(message):
    with _LOCK:
        _PROTOCOL.write(json.dumps(message, ensure_ascii=False) + "\n")
        _PROTOCOL.flush()


class _Redirect(io.TextIOBase):
    # Program output travels as messages so it cannot be mistaken for protocol.

    def __init__(self, name):
        self.name_ = name
        self._buffer = []

    def write(self, text):
        if not text:
            return 0
        self._buffer.append(text)
        if "\n" in text:
            self.flush()
        return len(text)

    def flush(self):
        if self._buffer:
            text = "".join(self._buffer)
            self._buffer = []
            _send({"t": "output", "name": self.name_, "text": text})
        return None


_stdout = _Redirect("stdout")
_stderr = _Redirect("stderr")


def _describe(value):
    try:
        text = repr(value)
    except Exception:
        return "<unrepresentable>"
    return text if len(text) <= 200 else text[:197] + "..."


class Debugger(bdb.Bdb):

    def __init__(self, script):
        bdb.Bdb.__init__(self)
        self.script = self.canonic(os.path.abspath(script))
        self.quitting_now = False
        # bdb stops on the very first line it traces. Starting a session should
        # run to the first breakpoint instead, the way -exec-run does.
        self.first_line = True

    # Gates every stop, so stepping never lands inside the standard library and
    # an exception caught by importlib during "import math" is not reported as
    # the user's. Breakpoints go through break_here and are unaffected.
    def stop_here(self, frame):
        if self.canonic(frame.f_code.co_filename) != self.script:
            return False
        return bdb.Bdb.stop_here(self, frame)

    def user_line(self, frame):
        if self.first_line:
            self.first_line = False
            self.set_continue()
            return
        self._pause(frame, "step")

    def user_return(self, frame, value):
        pass

    def user_exception(self, frame, exc_info):
        kind, value, tb = exc_info
        _send({"t": "exception", "ename": kind.__name__, "evalue": str(value),
               "traceback": traceback.format_exception(kind, value, tb)})
        self._pause(frame, "exception")

    def _pause(self, frame, reason):
        _stdout.flush()
        _stderr.flush()
        stack = []
        f = frame
        while f is not None:
            name = f.f_code.co_filename
            stack.append({"func": f.f_code.co_name, "file": name,
                          "line": f.f_lineno})
            if f.f_code.co_name == "<module>":
                break
            f = f.f_back
        variables = {}
        for key, value in list(frame.f_locals.items()):
            if not key.startswith("__"):
                variables[key] = _describe(value)
        _send({"t": "stopped", "reason": reason, "file": frame.f_code.co_filename,
               "line": frame.f_lineno, "func": frame.f_code.co_name,
               "stack": stack, "locals": variables})
        self._await_command(frame)

    def _await_command(self, frame):
        while True:
            message = _commands.get()
            op = message.get("op")
            if op == "continue":
                self.set_continue()
                return
            if op == "next":
                self.set_next(frame)
                return
            if op == "step":
                self.set_step()
                return
            if op == "return":
                self.set_return(frame)
                return
            if op == "terminate":
                self.quitting_now = True
                self.set_quit()
                return
            if op == "break":
                self.set_break(self.script, message.get("line"))
                _send({"t": "breakpoint", "line": message.get("line"), "set": True})
            elif op == "clear":
                self.clear_break(self.script, message.get("line"))
                _send({"t": "breakpoint", "line": message.get("line"), "set": False})


def _read_commands():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            _commands.put(json.loads(line))
        except Exception:
            continue
    _commands.put({"op": "terminate"})


def main():
    script = sys.argv[1]
    arguments = sys.argv[2:]
    debugger = Debugger(script)

    reader = threading.Thread(target=_read_commands, name="command-reader", daemon=True)
    reader.start()

    # Breakpoints and the run order arrive before anything is executed.
    while True:
        message = _commands.get()
        op = message.get("op")
        if op == "break":
            debugger.set_break(os.path.abspath(script), message.get("line"))
            _send({"t": "breakpoint", "line": message.get("line"), "set": True})
        elif op == "clear":
            debugger.clear_break(os.path.abspath(script), message.get("line"))
        elif op == "run":
            break
        elif op == "terminate":
            _send({"t": "exited", "code": 0})
            return

    _send({"t": "running"})
    sys.argv = [script] + arguments
    sys.stdout = _stdout
    sys.stderr = _stderr
    code = 0
    try:
        full = os.path.abspath(script)
        with open(full, "rb") as handle:
            source = handle.read()
        linecache.checkcache(full)
        # Compiled under the absolute path: a relative one leaves co_filename
        # different from the breakpoint keys, and nothing ever matches.
        globals_ = {"__name__": "__main__", "__file__": full, "__builtins__": __builtins__}
        debugger.run(compile(source, full, "exec"), globals_, globals_)
    except bdb.BdbQuit:
        code = -1
    except SystemExit as exit_request:
        code = exit_request.code if isinstance(exit_request.code, int) else 0
    except BaseException:
        kind, value, tb = sys.exc_info()
        _stderr.write("".join(traceback.format_exception(kind, value, tb)))
        code = 1
    finally:
        _stdout.flush()
        _stderr.flush()
        sys.stdout = _PROTOCOL
        sys.stderr = sys.__stderr__
        _send({"t": "exited", "code": code})


if __name__ == "__main__":
    main()
