package com.sphere.components.rootview;

import javax.imageio.ImageIO;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

/** Turns what is on screen into a file someone else can use. */
public final class RootExport {

    private RootExport() {
    }

    public static void saveText(Path target, String content) throws IOException {
        Files.writeString(target, content, StandardCharsets.UTF_8);
    }

    public static void savePng(Path target, RootPlot plot, int width, int height)
            throws IOException {
        ImageIO.write(plot.snapshot(width, height), "png", target.toFile());
    }

    /** The ROOT macro that opens the file and draws this object. */
    public static String macroFor(Path file, String path, String className,
                                  RootPlot.Style style, boolean logX, boolean logY,
                                  int rebin) {
        final String name = path.contains("/")
            ? path.substring(path.lastIndexOf('/') + 1) : path;
        final String variable = safeName(name);
        final String inner = path.contains("/")
            ? path.substring(path.indexOf('/') + 1) : path;

        StringBuilder b = new StringBuilder();
        b.append("// Generated by Sphere. Run with: root -l ")
         .append(variable).append(".C\n");
        b.append("void ").append(variable).append("() {\n");
        b.append("    TFile *f = TFile::Open(\"")
         .append(file.toAbsolutePath().toString().replace("\\", "\\\\"))
         .append("\");\n");
        b.append("    if (!f || f->IsZombie()) { return; }\n\n");
        b.append("    auto *o = f->Get<").append(className).append(">(\"")
         .append(inner).append("\");\n");
        b.append("    if (!o) { return; }\n\n");
        b.append("    TCanvas *c = new TCanvas(\"c\", \"").append(name)
         .append("\", 900, 640);\n");
        if (logX) {
            b.append("    c->SetLogx();\n");
        }
        if (logY) {
            b.append("    c->SetLogy();\n");
        }
        b.append("    c->SetGrid();\n\n");

        if (className.startsWith("TH") && rebin > 1) {
            b.append("    o->Rebin(").append(rebin).append(");\n");
        }
        b.append("    o->Draw(\"").append(drawOption(className, style))
         .append("\");\n");
        b.append("}\n");
        return b.toString();
    }

    private static String drawOption(String className, RootPlot.Style style) {
        if (className.startsWith("TGraph")) {
            return switch (style) {
                case LINE -> "AL";
                case STEPS -> "AL";
                default -> "AP";
            };
        }
        return switch (style) {
            case BARS -> "HIST";
            case STEPS -> "HIST";
            case POINTS -> "E1";
            case LINE -> "C";
        };
    }

    /** The same drawing in Python, for anyone working from a notebook. */
    public static String pythonFor(Path file, String path, String className,
                                   boolean logY, int rebin) {
        final String inner = path.contains("/")
            ? path.substring(path.indexOf('/') + 1) : path;
        StringBuilder b = new StringBuilder();
        b.append("# Generated by Sphere\n");
        b.append("import uproot\n");
        b.append("import matplotlib.pyplot as plt\n\n");
        b.append("f = uproot.open(r\"").append(file.toAbsolutePath()).append("\")\n");
        b.append("o = f[\"").append(inner).append("\"]\n\n");
        if (className.startsWith("TGraph")) {
            b.append("x, y = o.values()\n");
            b.append("plt.plot(x, y, \"o\")\n");
        } else {
            b.append("counts, edges = o.to_numpy()\n");
            if (rebin > 1) {
                b.append("counts = counts[:len(counts) // ").append(rebin)
                 .append(" * ").append(rebin).append("].reshape(-1, ")
                 .append(rebin).append(").sum(axis=1)\n");
                b.append("edges = edges[::").append(rebin).append("]\n");
            }
            b.append("plt.stairs(counts, edges, fill=True)\n");
        }
        if (logY) {
            b.append("plt.yscale(\"log\")\n");
        }
        b.append("plt.title(\"").append(path).append("\")\n");
        b.append("plt.show()\n");
        return b.toString();
    }

    /** A summary of the file, the kind of thing that goes in a logbook. */
    public static String report(RootFile file, RootNode root) {
        StringBuilder b = new StringBuilder();
        b.append(file.getPath().getFileName()).append('\n');
        b.append(String.format(Locale.ROOT, "%,d bytes, format %d, %s level %d%n",
                 file.getSize(), file.getFormatVersion(),
                 RootFile.compressionName(file.getCompressionAlgorithm()),
                 file.getCompressionLevel()));
        b.append('\n');
        describe(root, "", b);
        return b.toString();
    }

    private static void describe(RootNode node, String indent, StringBuilder b) {
        for (RootNode child : node.children) {
            if (child.directory) {
                b.append(indent).append(child.name).append("/\n");
                describe(child, indent + "    ", b);
            } else {
                b.append(String.format(Locale.ROOT, "%s%-18s %-22s %s%n",
                         indent, child.className, child.name, child.title));
            }
        }
    }

    private static String safeName(String text) {
        StringBuilder b = new StringBuilder();
        for (char c : text.toCharArray()) {
            b.append(Character.isLetterOrDigit(c) ? c : '_');
        }
        if (b.length() == 0 || Character.isDigit(b.charAt(0))) {
            b.insert(0, 'x');
        }
        return b.toString();
    }
}
