# Sphere JupyLab kernel driver.
#
# Keeps one interpreter alive for the whole notebook and talks to Sphere over
# stdin/stdout, one JSON message per line. No Jupyter, ipykernel or ZMQ needed.
# Regenerated by Sphere when missing; edit only if you know what you are doing.
SPHERE_KERNEL_VERSION = 1

import _thread
import ast
import base64
import builtins
import io
import json
import linecache
import os
import queue
import signal
import sys
import threading
import time
import traceback

_PROTOCOL = sys.__stdout__
_LOCK = threading.RLock()


def _send(message):
    # One JSON object per line on the real stdout, which only we write to.
    with _LOCK:
        _PROTOCOL.write(json.dumps(message, ensure_ascii=False) + "\n")
        _PROTOCOL.flush()


class _StreamRedirect(io.TextIOBase):
    # User prints become stream messages instead of raw pipe bytes. Writes are
    # joined until a newline: print('a =', 1) reaches write() four times, and one
    # message per fragment would mean four repaints for one line of output.
    #

    LIMIT = 8192

    def __init__(self, name):
        self.name_ = name
        self.exec_id = None
        self._buffer = []
        self._size = 0

    def write(self, text):
        if not text:
            return 0
        self._buffer.append(text)
        self._size += len(text)
        if "\n" in text or self._size >= self.LIMIT:
            self.flush()
        return len(text)

    def flush(self):
        if not self._buffer:
            return None
        text = "".join(self._buffer)
        self._buffer = []
        self._size = 0
        _send({"t": "stream", "id": self.exec_id, "name": self.name_, "text": text})
        return None

    def isatty(self):
        return False


_stdout = _StreamRedirect("stdout")
_stderr = _StreamRedirect("stderr")
sys.stdout = _stdout
sys.stderr = _stderr

_input_replies = queue.Queue()


def _input(prompt=""):
    # input() used to block forever on a pipe nobody wrote to.
    _stdout.flush()
    _send({"t": "input", "id": _stdout.exec_id, "prompt": str(prompt)})
    return _input_replies.get()


builtins.input = _input

_namespace = {"__name__": "__main__", "__builtins__": builtins}
_execution_count = 0
_requests = queue.Queue()


def _register_source(cell_name, code):
    # linecache lets a traceback show the offending line of the cell itself.
    lines = [line + "\n" for line in code.split("\n")]
    linecache.cache[cell_name] = (len(code), None, lines, cell_name)


def _rich(value):
    # The mime bundle for a value, richest form first.
    bundle = {}
    for method, mime in (("_repr_html_", "text/html"),
                         ("_repr_latex_", "text/latex"),
                         ("_repr_svg_", "image/svg+xml")):
        renderer = getattr(value, method, None)
        if callable(renderer):
            try:
                rendered = renderer()
                if rendered:
                    bundle[mime] = rendered
            except Exception:
                pass
    png = getattr(value, "_repr_png_", None)
    if callable(png):
        try:
            raw = png()
            if raw:
                bundle["image/png"] = base64.b64encode(raw).decode("ascii")
        except Exception:
            pass
    try:
        bundle["text/plain"] = repr(value)
    except Exception:
        bundle["text/plain"] = "<unrepresentable object>"
    return bundle


def _flush_figures(exec_id):
    # Matplotlib figures used to travel as a sentinel inside stdout.
    plt = sys.modules.get("matplotlib.pyplot")
    if plt is None:
        return
    try:
        for number in plt.get_fignums():
            figure = plt.figure(number)
            buffer = io.BytesIO()
            figure.savefig(buffer, format="png", bbox_inches="tight")
            _send({"t": "display", "id": exec_id, "bundle":
                   {"image/png": base64.b64encode(buffer.getvalue()).decode("ascii")}})
        plt.close("all")
    except Exception:
        pass


def _format_error(cell_name, exc_type, exc_value, tb):
    # The driver's own frame is dropped so the trace starts in the user's cell.
    frames = tb.tb_next if tb is not None and tb.tb_next is not None else tb
    lines = traceback.format_exception(exc_type, exc_value, frames)
    return {"ename": exc_type.__name__,
            "evalue": str(exc_value),
            "traceback": [line for line in
                          "".join(lines).rstrip("\n").split("\n")]}


def _execute(exec_id, code):
    global _execution_count
    cell_name = "<cell %d>" % exec_id
    _register_source(cell_name, code)
    _stdout.exec_id = exec_id
    _stderr.exec_id = exec_id
    started = time.perf_counter()
    try:
        tree = ast.parse(code, filename=cell_name, mode="exec")
    except SyntaxError:
        _send(dict({"t": "error", "id": exec_id},
                   **_format_error(cell_name, *sys.exc_info())))
        _send({"t": "done", "id": exec_id, "count": None,
               "ms": int((time.perf_counter() - started) * 1000)})
        return

    tail = None
    # A cell ending in an expression displays its value, the way a notebook does.
    if tree.body and isinstance(tree.body[-1], ast.Expr):
        tail = ast.Expression(tree.body.pop().value)
        ast.copy_location(tail, tail.body)

    _execution_count += 1
    count = _execution_count
    try:
        if tree.body:
            exec(compile(tree, cell_name, "exec"), _namespace)
        if tail is not None:
            value = eval(compile(tail, cell_name, "eval"), _namespace)
            if value is not None:
                _namespace["_"] = value
                _send({"t": "result", "id": exec_id, "count": count,
                       "bundle": _rich(value)})
    except KeyboardInterrupt:
        _send({"t": "error", "id": exec_id, "ename": "KeyboardInterrupt",
               "evalue": "execution interrupted", "traceback": []})
    except BaseException:
        _send(dict({"t": "error", "id": exec_id},
                   **_format_error(cell_name, *sys.exc_info())))
    finally:
        _stdout.flush()
        _stderr.flush()
        _flush_figures(exec_id)
        _send({"t": "done", "id": exec_id, "count": count,
               "ms": int((time.perf_counter() - started) * 1000)})


def _complete(exec_id, code, cursor):
    # Completion asks the live namespace, so it knows what the objects hold.
    import re
    import rlcompleter
    prefix = code[:cursor]
    match = re.search(r"[A-Za-z_][A-Za-z0-9_\.]*$", prefix)
    token = match.group(0) if match else ""
    completer = rlcompleter.Completer(_namespace)
    matches = []
    try:
        index = 0
        while True:
            candidate = completer.complete(token, index)
            if candidate is None or index > 200:
                break
            if candidate not in matches:
                matches.append(candidate)
            index += 1
    except Exception:
        pass
    _send({"t": "complete", "id": exec_id, "start": cursor - len(token),
           "matches": matches})


def _describe(value):
    # A short shape for the inspector, without importing numpy or pandas.
    kind = type(value).__name__
    try:
        shape = getattr(value, "shape", None)
        if shape is not None:
            return kind, "%s %s" % (getattr(getattr(value, "dtype", ""), "name", ""),
                                    tuple(shape))
        if isinstance(value, (list, tuple, set, dict)):
            return kind, "%d elements" % len(value)
        text = repr(value)
        return kind, text if len(text) <= 80 else text[:77] + "..."
    except Exception:
        return kind, ""


def _variables(exec_id):
    items = []
    for name, value in list(_namespace.items()):
        if name.startswith("__") or name == "_":
            continue
        import types
        if isinstance(value, types.ModuleType) or callable(value) and isinstance(
                value, (types.FunctionType, types.BuiltinFunctionType, type)):
            continue
        kind, info = _describe(value)
        items.append({"name": name, "type": kind, "info": info})
    items.sort(key=lambda item: item["name"])
    _send({"t": "vars", "id": exec_id, "items": items})


def _interrupt():
    # Stops the running cell. The interrupt has to reach the process, not just the
    # thread that asks for it: interrupt_main and raise_signal only set a flag the
    # main thread reads at its next check, so a cell blocked in time.sleep kept
    # sleeping to the end. A real SIGINT breaks the blocking call itself.
    #
    try:
        if os.name == "nt":
            # No process-directed signal on Windows; CPython's own handler wakes
            # the sleeping main thread through its interrupt event.
            signal.raise_signal(signal.SIGINT)
        else:
            os.kill(os.getpid(), signal.SIGINT)
    except Exception:
        _thread.interrupt_main()


def _reset():
    global _namespace, _execution_count
    _namespace = {"__name__": "__main__", "__builtins__": builtins}
    _execution_count = 0
    _send({"t": "reset"})


def _read_commands():
    # Reads Sphere's messages while a cell is running. Everything that must reach a
    # busy kernel -- an interrupt, an answer to input() -- arrives on this thread.
    #
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            message = json.loads(line)
        except Exception:
            continue
        op = message.get("op")
        if op == "exec":
            _requests.put(message)
        elif op == "input":
            _input_replies.put(message.get("text", ""))
        elif op == "interrupt":
            _interrupt()
        elif op == "complete":
            _complete(message.get("id"), message.get("code", ""),
                      message.get("cursor", 0))
        elif op == "vars":
            _variables(message.get("id"))
        elif op == "reset":
            _requests.put({"op": "reset"})
        elif op == "shutdown":
            _requests.put({"op": "shutdown"})
            return
    _requests.put({"op": "shutdown"})


def main():
    _send({"t": "ready", "version": SPHERE_KERNEL_VERSION,
           "python": sys.version.split()[0], "executable": sys.executable})
    reader = threading.Thread(target=_read_commands, name="command-reader", daemon=True)
    reader.start()
    while True:
        try:
            request = _requests.get()
        except KeyboardInterrupt:
            # An interrupt that arrived between two cells has nothing to stop.
            continue
        op = request.get("op")
        if op == "shutdown":
            return
        if op == "reset":
            _reset()
        elif op == "exec":
            _execute(request.get("id"), request.get("code", ""))


if __name__ == "__main__":
    main()
