package com.sphere.core.python.jupyterlab.kernel;

import com.sphere.utils.AppLogger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * The Python side of the kernel. Carried here so the notebook cannot break by
 * losing a file, and written out to config/ so it stays readable and adaptable.
 */
public final class KernelScript {

    /** Bumped whenever the source below changes, so a stale copy is rewritten. */
    public static final int VERSION = 2;

    public static final String FILE_NAME = "jupylab_kernel.py";

    /** Bumped whenever SHM_SOURCE below changes. */
    public static final int SHM_VERSION = 1;

    public static final String SHM_FILE_NAME = "sphere_shm.py";

    private KernelScript() {
    }

    /**
     * Path of the driver on disk, written or refreshed as needed. The version
     * marker on the first lines is what tells a stale copy from a current one.
     */
    public static Path materialize() throws IOException {
        Path directory = Path.of("config");
        Files.createDirectories(directory);
        Path script = directory.resolve(FILE_NAME);
        if (Files.isReadable(script)) {
            String existing = Files.readString(script, StandardCharsets.UTF_8);
            if (existing.contains("SPHERE_KERNEL_VERSION = " + VERSION)) {
                return script;
            }
            AppLogger.info("JupyLab kernel driver refreshed to version " + VERSION + ".");
        }
        Files.writeString(script, SOURCE, StandardCharsets.UTF_8);
        return script;
    }

    /**
     * Writes the shared-memory module beside the driver, which imports it from
     * its own directory. A kernel started without a region still runs: the module
     * is there, it simply has nothing to attach to.
     */
    public static Path materializeShm() throws IOException {
        Path directory = Path.of("config");
        Files.createDirectories(directory);
        Path module = directory.resolve(SHM_FILE_NAME);
        if (Files.isReadable(module)) {
            String existing = Files.readString(module, StandardCharsets.UTF_8);
            if (existing.contains("SPHERE_SHM_VERSION = " + SHM_VERSION)) {
                return module;
            }
            AppLogger.info("Sphere shared-memory module refreshed to version "
                           + SHM_VERSION + ".");
        }
        Files.writeString(module, SHM_SOURCE, StandardCharsets.UTF_8);
        return module;
    }

    private static final String SOURCE = """
# Sphere JupyLab kernel driver.
#
# Keeps one interpreter alive for the whole notebook and talks to Sphere over
# stdin/stdout, one JSON message per line. No Jupyter, ipykernel or ZMQ needed.
# Regenerated by Sphere when missing; edit only if you know what you are doing.
SPHERE_KERNEL_VERSION = 1

import _thread
import ast
import base64
import builtins
import io
import json
import linecache
import os
import queue
import signal
import sys
import threading
import time
import traceback

_PROTOCOL = sys.__stdout__
_LOCK = threading.RLock()


def _send(message):
    # One JSON object per line on the real stdout, which only we write to.
    with _LOCK:
        _PROTOCOL.write(json.dumps(message, ensure_ascii=False) + "\\n")
        _PROTOCOL.flush()


class _StreamRedirect(io.TextIOBase):
    # User prints become stream messages instead of raw pipe bytes. Writes are
    # joined until a newline: print('a =', 1) reaches write() four times, and one
    # message per fragment would mean four repaints for one line of output.
    #

    LIMIT = 8192

    def __init__(self, name):
        self.name_ = name
        self.exec_id = None
        self._buffer = []
        self._size = 0

    def write(self, text):
        if not text:
            return 0
        self._buffer.append(text)
        self._size += len(text)
        if "\\n" in text or self._size >= self.LIMIT:
            self.flush()
        return len(text)

    def flush(self):
        if not self._buffer:
            return None
        text = "".join(self._buffer)
        self._buffer = []
        self._size = 0
        _send({"t": "stream", "id": self.exec_id, "name": self.name_, "text": text})
        return None

    def isatty(self):
        return False


_stdout = _StreamRedirect("stdout")
_stderr = _StreamRedirect("stderr")
sys.stdout = _stdout
sys.stderr = _stderr

_input_replies = queue.Queue()


def _input(prompt=""):
    # input() used to block forever on a pipe nobody wrote to.
    _stdout.flush()
    _send({"t": "input", "id": _stdout.exec_id, "prompt": str(prompt)})
    return _input_replies.get()


builtins.input = _input

_namespace = {"__name__": "__main__", "__builtins__": builtins}
_execution_count = 0
_requests = queue.Queue()


def _register_source(cell_name, code):
    # linecache lets a traceback show the offending line of the cell itself.
    lines = [line + "\\n" for line in code.split("\\n")]
    linecache.cache[cell_name] = (len(code), None, lines, cell_name)


def _rich(value):
    # The mime bundle for a value, richest form first.
    bundle = {}
    for method, mime in (("_repr_html_", "text/html"),
                         ("_repr_latex_", "text/latex"),
                         ("_repr_svg_", "image/svg+xml")):
        renderer = getattr(value, method, None)
        if callable(renderer):
            try:
                rendered = renderer()
                if rendered:
                    bundle[mime] = rendered
            except Exception:
                pass
    png = getattr(value, "_repr_png_", None)
    if callable(png):
        try:
            raw = png()
            if raw:
                bundle["image/png"] = base64.b64encode(raw).decode("ascii")
        except Exception:
            pass
    try:
        bundle["text/plain"] = repr(value)
    except Exception:
        bundle["text/plain"] = "<unrepresentable object>"
    return bundle


def _flush_figures(exec_id):
    # Matplotlib figures used to travel as a sentinel inside stdout.
    plt = sys.modules.get("matplotlib.pyplot")
    if plt is None:
        return
    try:
        for number in plt.get_fignums():
            figure = plt.figure(number)
            buffer = io.BytesIO()
            figure.savefig(buffer, format="png", bbox_inches="tight")
            _send({"t": "display", "id": exec_id, "bundle":
                   {"image/png": base64.b64encode(buffer.getvalue()).decode("ascii")}})
        plt.close("all")
    except Exception:
        pass


def _format_error(cell_name, exc_type, exc_value, tb):
    # The driver's own frame is dropped so the trace starts in the user's cell.
    frames = tb.tb_next if tb is not None and tb.tb_next is not None else tb
    lines = traceback.format_exception(exc_type, exc_value, frames)
    return {"ename": exc_type.__name__,
            "evalue": str(exc_value),
            "traceback": [line for line in
                          "".join(lines).rstrip("\\n").split("\\n")]}


def _execute(exec_id, code):
    global _execution_count
    cell_name = "<cell %d>" % exec_id
    _register_source(cell_name, code)
    _stdout.exec_id = exec_id
    _stderr.exec_id = exec_id
    started = time.perf_counter()
    try:
        tree = ast.parse(code, filename=cell_name, mode="exec")
    except SyntaxError:
        _send(dict({"t": "error", "id": exec_id},
                   **_format_error(cell_name, *sys.exc_info())))
        _send({"t": "done", "id": exec_id, "count": None,
               "ms": int((time.perf_counter() - started) * 1000)})
        return

    tail = None
    # A cell ending in an expression displays its value, the way a notebook does.
    if tree.body and isinstance(tree.body[-1], ast.Expr):
        tail = ast.Expression(tree.body.pop().value)
        ast.copy_location(tail, tail.body)

    _execution_count += 1
    count = _execution_count
    try:
        if tree.body:
            exec(compile(tree, cell_name, "exec"), _namespace)
        if tail is not None:
            value = eval(compile(tail, cell_name, "eval"), _namespace)
            if value is not None:
                _namespace["_"] = value
                _send({"t": "result", "id": exec_id, "count": count,
                       "bundle": _rich(value)})
    except KeyboardInterrupt:
        _send({"t": "error", "id": exec_id, "ename": "KeyboardInterrupt",
               "evalue": "execution interrupted", "traceback": []})
    except BaseException:
        _send(dict({"t": "error", "id": exec_id},
                   **_format_error(cell_name, *sys.exc_info())))
    finally:
        _stdout.flush()
        _stderr.flush()
        _flush_figures(exec_id)
        _send({"t": "done", "id": exec_id, "count": count,
               "ms": int((time.perf_counter() - started) * 1000)})


def _complete(exec_id, code, cursor):
    # Completion asks the live namespace, so it knows what the objects hold.
    import re
    import rlcompleter
    prefix = code[:cursor]
    match = re.search(r"[A-Za-z_][A-Za-z0-9_\\.]*$", prefix)
    token = match.group(0) if match else ""
    completer = rlcompleter.Completer(_namespace)
    matches = []
    try:
        index = 0
        while True:
            candidate = completer.complete(token, index)
            if candidate is None or index > 200:
                break
            if candidate not in matches:
                matches.append(candidate)
            index += 1
    except Exception:
        pass
    _send({"t": "complete", "id": exec_id, "start": cursor - len(token),
           "matches": matches})


def _describe(value):
    # A short shape for the inspector, without importing numpy or pandas.
    kind = type(value).__name__
    try:
        shape = getattr(value, "shape", None)
        if shape is not None:
            return kind, "%s %s" % (getattr(getattr(value, "dtype", ""), "name", ""),
                                    tuple(shape))
        if isinstance(value, (list, tuple, set, dict)):
            return kind, "%d elements" % len(value)
        text = repr(value)
        return kind, text if len(text) <= 80 else text[:77] + "..."
    except Exception:
        return kind, ""


def _variables(exec_id):
    items = []
    for name, value in list(_namespace.items()):
        if name.startswith("__") or name == "_":
            continue
        import types
        if isinstance(value, types.ModuleType) or callable(value) and isinstance(
                value, (types.FunctionType, types.BuiltinFunctionType, type)):
            continue
        kind, info = _describe(value)
        items.append({"name": name, "type": kind, "info": info})
    items.sort(key=lambda item: item["name"])
    _send({"t": "vars", "id": exec_id, "items": items})


def _interrupt():
    # Stops the running cell. The interrupt has to reach the process, not just the
    # thread that asks for it: interrupt_main and raise_signal only set a flag the
    # main thread reads at its next check, so a cell blocked in time.sleep kept
    # sleeping to the end. A real SIGINT breaks the blocking call itself.
    #
    try:
        if os.name == "nt":
            # No process-directed signal on Windows; CPython's own handler wakes
            # the sleeping main thread through its interrupt event.
            signal.raise_signal(signal.SIGINT)
        else:
            os.kill(os.getpid(), signal.SIGINT)
    except Exception:
        _thread.interrupt_main()


def _reset():
    global _namespace, _execution_count
    _namespace = {"__name__": "__main__", "__builtins__": builtins}
    _execution_count = 0
    _send({"t": "reset"})


_shm_replies = {}
_shm_event = threading.Event()


def _shm_wait_for(rid, timeout=10.0):
    # The reply arrives on the reader thread, so this waits rather than reads.
    deadline = time.monotonic() + timeout
    while True:
        if rid in _shm_replies:
            return _shm_replies.pop(rid)
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError(f"Sphere did not answer shared-memory request {rid}")
        _shm_event.wait(remaining)
        _shm_event.clear()


def _install_shm():
    # Optional: a kernel started without a shared region simply has no module.
    if not os.environ.get("SPHERE_SHM_PATH"):
        return
    try:
        import sphere_shm
    except ImportError:
        return
    sphere_shm.set_broker_factory(
        lambda: sphere_shm.KernelBroker(_send, _shm_wait_for))
    builtins.sphere_shm = sphere_shm


def _read_commands():
    # Reads Sphere's messages while a cell is running. Everything that must reach a
    # busy kernel -- an interrupt, an answer to input() -- arrives on this thread.
    #
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            message = json.loads(line)
        except Exception:
            continue
        op = message.get("op")
        if op == "shm_reply":
            _shm_replies[message.get("rid")] = message
            _shm_event.set()
            continue
        if op == "exec":
            _requests.put(message)
        elif op == "input":
            _input_replies.put(message.get("text", ""))
        elif op == "interrupt":
            _interrupt()
        elif op == "complete":
            _complete(message.get("id"), message.get("code", ""),
                      message.get("cursor", 0))
        elif op == "vars":
            _variables(message.get("id"))
        elif op == "reset":
            _requests.put({"op": "reset"})
        elif op == "shutdown":
            _requests.put({"op": "shutdown"})
            return
    _requests.put({"op": "shutdown"})


def main():
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    _install_shm()
    _send({"t": "ready", "version": SPHERE_KERNEL_VERSION,
           "python": sys.version.split()[0], "executable": sys.executable})
    reader = threading.Thread(target=_read_commands, name="command-reader", daemon=True)
    reader.start()
    while True:
        try:
            request = _requests.get()
        except KeyboardInterrupt:
            # An interrupt that arrived between two cells has nothing to stop.
            continue
        op = request.get("op")
        if op == "shutdown":
            return
        if op == "reset":
            _reset()
        elif op == "exec":
            _execute(request.get("id"), request.get("code", ""))


if __name__ == "__main__":
    main()
""";

    private static final String SHM_SOURCE = """
# Sphere shared-memory bridge for the notebook kernel.
#
# Turns a block of the engine's shared region into a numpy array without copying
# a byte, and hands it to PyTorch, TensorFlow or JAX through DLPack. Blocks are
# obtained from and returned to the Java side, which owns the allocator: writing
# a third lock-free allocator in Python would be one implementation too many, and
# the round trip costs a fraction of a millisecond against a transfer that would
# otherwise copy megabytes.
#
# Regenerated by Sphere when missing; edit only if you know what you are doing.
SPHERE_SHM_VERSION = 1

import mmap
import os
import struct
import weakref

# ---------------------------------------------------------------------------
# Region layout, mirroring inc/shm_layout.h and inc/common_config.h
# ---------------------------------------------------------------------------

SHM_MAGIC = 0x53504852
SHM_VERSION = 3
CHUNK_MAGIC = 0x43484E4B
CHUNK_HEADER_SIZE = 128
CHUNK_FREE = 8
SHM_OFFSET_SHIFT = 6

HDR_MAGIC_OFF = 0
HDR_VERSION_OFF = 4
HDR_OFF_DATA_HEAP = 584

CHUNK_MAGIC_OFF = 0
CHUNK_SIZE_OFF = 4
CHUNK_KIND_OFF = 16
CHUNK_FLAGS_OFF = 22
CHUNK_GENERATION_OFF = 28

# ShmDType in inc/lockfree_ring.h, paired with what each framework calls it.
# bfloat16 has no numpy dtype of its own; ml_dtypes supplies one when installed,
# and without it a bfloat16 block is refused rather than silently misread.
_DTYPE_TABLE = {
    0: ("float32", 4),
    1: ("float16", 2),
    2: ("int32", 4),
    3: ("int64", 8),
    4: ("uint8", 1),
    5: ("bfloat16", 2),
    6: ("float64", 8),
    7: ("uint32", 4),
    8: ("uint64", 8),
    9: ("int16", 2),
    10: ("uint16", 2),
    11: ("int8", 1),
}

_DTYPE_CODES = {name: code for code, (name, _) in _DTYPE_TABLE.items()}


class ShmError(RuntimeError):
    pass


def _numpy():
    import numpy as np
    return np


def _numpy_dtype(name):
    np = _numpy()
    if name == "bfloat16":
        try:
            import ml_dtypes
        except ImportError as exc:
            raise ShmError(
                "bfloat16 blocks need the ml_dtypes package, which gives numpy a "
                "bfloat16 dtype; PyTorch and TensorFlow read it through DLPack "
                "once it is installed."
            ) from exc
        return ml_dtypes.bfloat16
    return np.dtype(name)


# ---------------------------------------------------------------------------
# Blocks
# ---------------------------------------------------------------------------

class ShmArray:
    \"\"\"Placeholder replaced below once numpy is available.\"\"\"


def _shm_array_class():
    \"\"\"The ndarray subclass that carries the owning block.

    A plain ndarray takes no attributes, and the block has to stay reachable for
    as long as any view of it does: the release fires when the last one goes.
    \"\"\"
    global ShmArray
    if not isinstance(ShmArray, type) or not hasattr(ShmArray, "__array_finalize__"):
        np = _numpy()

        class _ShmArray(np.ndarray):
            block = None

            def __array_finalize__(self, obj):
                if obj is not None:
                    self.block = getattr(obj, "block", None)

        ShmArray = _ShmArray
    return ShmArray


class Block:
    \"\"\"One block of the shared region, alive for as long as anything reads it.

    numpy keeps this object referenced through ``array.base``, and every tensor
    built from that array keeps the array. So the block is returned to the engine
    when the last view goes away, not when this object leaves scope.
    \"\"\"

    __slots__ = ("_region", "_offset", "_generation", "_nbytes", "_dtype",
                 "_shape", "_view", "_finalizer", "__weakref__")

    def __init__(self, region, offset, generation, nbytes, dtype, shape, on_release):
        self._region = region
        self._offset = offset
        self._generation = generation
        self._nbytes = nbytes
        self._dtype = dtype
        self._shape = tuple(shape)
        self._view = memoryview(region.map)[offset:offset + nbytes]
        self._finalizer = weakref.finalize(self, on_release, offset, generation)

    @property
    def offset(self):
        return self._offset

    @property
    def generation(self):
        return self._generation

    @property
    def dtype(self):
        return self._dtype

    @property
    def shape(self):
        return self._shape

    def is_live(self):
        return self._region.handle_is_live(self._offset, self._generation)

    def array(self):
        \"\"\"The block as a writable numpy array. No bytes are copied.\"\"\"
        np = _numpy()
        if not self.is_live():
            raise ShmError(
                f"block at offset {self._offset} was recycled; its generation is "
                f"no longer {self._generation}"
            )
        dtype = _numpy_dtype(self._dtype)
        shape = self._shape if self._shape else (self._nbytes // np.dtype(dtype).itemsize,)
        # ndarray over the mapped bytes rather than frombuffer, which would hand
        # back a read-only view and make the write direction impossible.
        flat = np.ndarray(shape, dtype=dtype, buffer=self._view)
        view = flat.view(_shm_array_class())
        view.block = self
        return view

    def torch(self):
        \"\"\"A torch tensor over the same bytes.\"\"\"
        import torch
        return torch.from_dlpack(self.array())

    def tensorflow(self):
        \"\"\"A TensorFlow tensor over the same bytes.\"\"\"
        import tensorflow as tf
        return tf.experimental.dlpack.from_dlpack(self.array().__dlpack__())

    def release(self):
        \"\"\"Returns the block now instead of waiting for the collector.\"\"\"
        self._view.release()
        self._finalizer()

    def __len__(self):
        return self._nbytes

    def __repr__(self):
        return (f"<Block offset={self._offset} generation={self._generation} "
                f"{self._dtype}{list(self._shape)}>")


# ---------------------------------------------------------------------------
# Region
# ---------------------------------------------------------------------------

class Region:
    \"\"\"The mapped shared region, plus the channel that asks Java for blocks.\"\"\"

    def __init__(self, path, broker=None):
        self.path = path
        self._fd = os.open(path, os.O_RDWR)
        self.map = mmap.mmap(self._fd, 0)
        self._broker = broker

        magic = struct.unpack_from("<I", self.map, HDR_MAGIC_OFF)[0]
        version = struct.unpack_from("<I", self.map, HDR_VERSION_OFF)[0]
        if magic != SHM_MAGIC or version != SHM_VERSION:
            # Sphere lays the region out before starting a kernel, so this only
            # happens when the module is pointed somewhere it should not be.
            raise ShmError(f"{path} is not a shared region this kernel can read")
        self.heap_offset = struct.unpack_from("<Q", self.map, HDR_OFF_DATA_HEAP)[0]

    def close(self):
        self.map.close()
        os.close(self._fd)

    def handle_is_live(self, offset, generation):
        \"\"\"True while `offset` still names the block it was handed out for.\"\"\"
        base = offset - CHUNK_HEADER_SIZE
        if base < 0 or offset > len(self.map):
            return False
        if struct.unpack_from("<I", self.map, base + CHUNK_MAGIC_OFF)[0] != CHUNK_MAGIC:
            return False
        live = struct.unpack_from("<I", self.map, base + CHUNK_GENERATION_OFF)[0]
        flags = struct.unpack_from("<H", self.map, base + CHUNK_FLAGS_OFF)[0]
        return live == generation and (flags & CHUNK_FREE) == 0

    def attach(self, offset, generation, dtype, shape):
        \"\"\"Wraps a block the engine has already filled, for reading.\"\"\"
        if isinstance(dtype, int):
            dtype = _DTYPE_TABLE[dtype][0]
        nbytes = _itemsize(dtype)
        for extent in shape:
            nbytes *= extent
        if not self.handle_is_live(offset, generation):
            raise ShmError(f"block at offset {offset} is no longer generation {generation}")
        return Block(self, offset, generation, nbytes, dtype, shape, self._release)

    def allocate(self, dtype, shape):
        \"\"\"Asks Java for a block and hands it back writable, for sending data out.\"\"\"
        if self._broker is None:
            raise ShmError("no channel to the Java side: this kernel cannot allocate")
        if isinstance(dtype, int):
            dtype = _DTYPE_TABLE[dtype][0]
        if dtype not in _DTYPE_CODES:
            raise ShmError(f"unknown dtype {dtype!r}")
        nbytes = _itemsize(dtype)
        for extent in shape:
            nbytes *= extent
        offset, generation = self._broker.allocate(nbytes, _DTYPE_CODES[dtype])
        if offset == 0:
            raise ShmError(f"the engine refused a block of {nbytes} bytes")
        return Block(self, offset, generation, nbytes, dtype, shape, self._release)

    def _release(self, offset, generation):
        if self._broker is not None:
            self._broker.release(offset, generation)


def _itemsize(dtype):
    for name, size in _DTYPE_TABLE.values():
        if name == dtype:
            return size
    raise ShmError(f"unknown dtype {dtype!r}")


# ---------------------------------------------------------------------------
# The channel to Java, over the kernel's own line protocol
# ---------------------------------------------------------------------------

class KernelBroker:
    \"\"\"Asks the Java side to allocate and free, over the stdio line protocol.

    Java owns the allocator, so the CAS that claims a block happens in exactly one
    place. Only the request travels; the data never leaves the shared region.
    \"\"\"

    def __init__(self, send, wait_for):
        self._send = send
        self._wait_for = wait_for
        self._next_id = 0

    def _request(self, message):
        self._next_id += 1
        message["rid"] = self._next_id
        self._send(message)
        return self._wait_for(self._next_id)

    def allocate(self, nbytes, dtype_code):
        reply = self._request({"t": "shm_alloc", "bytes": nbytes, "dtype": dtype_code})
        return int(reply.get("offset", 0)), int(reply.get("generation", 0))

    def release(self, offset, generation):
        self._send({"t": "shm_release", "offset": offset, "generation": generation})


_REGION = None


def region():
    \"\"\"The region this kernel is attached to, opened on first use.\"\"\"
    global _REGION
    if _REGION is None:
        path = os.environ.get("SPHERE_SHM_PATH")
        if not path:
            raise ShmError("SPHERE_SHM_PATH is not set: Sphere did not attach this kernel")
        _REGION = Region(path, broker=_default_broker())
    return _REGION


_BROKER_FACTORY = None


def set_broker_factory(factory):
    \"\"\"Installed by the kernel driver, which owns the line protocol.\"\"\"
    global _BROKER_FACTORY
    _BROKER_FACTORY = factory


def _default_broker():
    return _BROKER_FACTORY() if _BROKER_FACTORY is not None else None


def attach(offset, generation, dtype, shape):
    return region().attach(offset, generation, dtype, shape)


def allocate(dtype, shape):
    return region().allocate(dtype, shape)
""";
}
