# Sphere shared-memory bridge for the notebook kernel.
#
# Turns a block of the engine's shared region into a numpy array without copying
# a byte, and hands it to PyTorch, TensorFlow or JAX through DLPack. Blocks are
# obtained from and returned to the Java side, which owns the allocator: writing
# a third lock-free allocator in Python would be one implementation too many, and
# the round trip costs a fraction of a millisecond against a transfer that would
# otherwise copy megabytes.
#
# Regenerated by Sphere when missing; edit only if you know what you are doing.
SPHERE_SHM_VERSION = 1

import mmap
import os
import struct
import weakref

# ---------------------------------------------------------------------------
# Region layout, mirroring inc/shm_layout.h and inc/common_config.h
# ---------------------------------------------------------------------------

SHM_MAGIC = 0x53504852
SHM_VERSION = 3
CHUNK_MAGIC = 0x43484E4B
CHUNK_HEADER_SIZE = 128
CHUNK_FREE = 8
SHM_OFFSET_SHIFT = 6

HDR_MAGIC_OFF = 0
HDR_VERSION_OFF = 4
HDR_OFF_DATA_HEAP = 584

CHUNK_MAGIC_OFF = 0
CHUNK_SIZE_OFF = 4
CHUNK_KIND_OFF = 16
CHUNK_FLAGS_OFF = 22
CHUNK_GENERATION_OFF = 28

# ShmDType in inc/lockfree_ring.h, paired with what each framework calls it.
# bfloat16 has no numpy dtype of its own; ml_dtypes supplies one when installed,
# and without it a bfloat16 block is refused rather than silently misread.
_DTYPE_TABLE = {
    0: ("float32", 4),
    1: ("float16", 2),
    2: ("int32", 4),
    3: ("int64", 8),
    4: ("uint8", 1),
    5: ("bfloat16", 2),
    6: ("float64", 8),
    7: ("uint32", 4),
    8: ("uint64", 8),
    9: ("int16", 2),
    10: ("uint16", 2),
    11: ("int8", 1),
}

_DTYPE_CODES = {name: code for code, (name, _) in _DTYPE_TABLE.items()}


class ShmError(RuntimeError):
    pass


def _numpy():
    import numpy as np
    return np


def _numpy_dtype(name):
    np = _numpy()
    if name == "bfloat16":
        try:
            import ml_dtypes
        except ImportError as exc:
            raise ShmError(
                "bfloat16 blocks need the ml_dtypes package, which gives numpy a "
                "bfloat16 dtype; PyTorch and TensorFlow read it through DLPack "
                "once it is installed."
            ) from exc
        return ml_dtypes.bfloat16
    return np.dtype(name)


# ---------------------------------------------------------------------------
# Blocks
# ---------------------------------------------------------------------------

class ShmArray:
    """Placeholder replaced below once numpy is available."""


def _shm_array_class():
    """The ndarray subclass that carries the owning block.

    A plain ndarray takes no attributes, and the block has to stay reachable for
    as long as any view of it does: the release fires when the last one goes.
    """
    global ShmArray
    if not isinstance(ShmArray, type) or not hasattr(ShmArray, "__array_finalize__"):
        np = _numpy()

        class _ShmArray(np.ndarray):
            block = None

            def __array_finalize__(self, obj):
                if obj is not None:
                    self.block = getattr(obj, "block", None)

        ShmArray = _ShmArray
    return ShmArray


class Block:
    """One block of the shared region, alive for as long as anything reads it.

    numpy keeps this object referenced through ``array.base``, and every tensor
    built from that array keeps the array. So the block is returned to the engine
    when the last view goes away, not when this object leaves scope.
    """

    __slots__ = ("_region", "_offset", "_generation", "_nbytes", "_dtype",
                 "_shape", "_view", "_finalizer", "__weakref__")

    def __init__(self, region, offset, generation, nbytes, dtype, shape, on_release):
        self._region = region
        self._offset = offset
        self._generation = generation
        self._nbytes = nbytes
        self._dtype = dtype
        self._shape = tuple(shape)
        self._view = memoryview(region.map)[offset:offset + nbytes]
        self._finalizer = weakref.finalize(self, on_release, offset, generation)

    @property
    def offset(self):
        return self._offset

    @property
    def generation(self):
        return self._generation

    @property
    def dtype(self):
        return self._dtype

    @property
    def shape(self):
        return self._shape

    def is_live(self):
        return self._region.handle_is_live(self._offset, self._generation)

    def array(self):
        """The block as a writable numpy array. No bytes are copied."""
        np = _numpy()
        if not self.is_live():
            raise ShmError(
                f"block at offset {self._offset} was recycled; its generation is "
                f"no longer {self._generation}"
            )
        dtype = _numpy_dtype(self._dtype)
        shape = self._shape if self._shape else (self._nbytes // np.dtype(dtype).itemsize,)
        # ndarray over the mapped bytes rather than frombuffer, which would hand
        # back a read-only view and make the write direction impossible.
        flat = np.ndarray(shape, dtype=dtype, buffer=self._view)
        view = flat.view(_shm_array_class())
        view.block = self
        return view

    def torch(self):
        """A torch tensor over the same bytes."""
        import torch
        return torch.from_dlpack(self.array())

    def tensorflow(self):
        """A TensorFlow tensor over the same bytes."""
        import tensorflow as tf
        return tf.experimental.dlpack.from_dlpack(self.array().__dlpack__())

    def release(self):
        """Returns the block now instead of waiting for the collector."""
        self._view.release()
        self._finalizer()

    def __len__(self):
        return self._nbytes

    def __repr__(self):
        return (f"<Block offset={self._offset} generation={self._generation} "
                f"{self._dtype}{list(self._shape)}>")


# ---------------------------------------------------------------------------
# Region
# ---------------------------------------------------------------------------

class Region:
    """The mapped shared region, plus the channel that asks Java for blocks."""

    def __init__(self, path, broker=None):
        self.path = path
        self._fd = os.open(path, os.O_RDWR)
        self.map = mmap.mmap(self._fd, 0)
        self._broker = broker

        magic = struct.unpack_from("<I", self.map, HDR_MAGIC_OFF)[0]
        version = struct.unpack_from("<I", self.map, HDR_VERSION_OFF)[0]
        if magic != SHM_MAGIC or version != SHM_VERSION:
            # Sphere lays the region out before starting a kernel, so this only
            # happens when the module is pointed somewhere it should not be.
            raise ShmError(f"{path} is not a shared region this kernel can read")
        self.heap_offset = struct.unpack_from("<Q", self.map, HDR_OFF_DATA_HEAP)[0]

    def close(self):
        self.map.close()
        os.close(self._fd)

    def handle_is_live(self, offset, generation):
        """True while `offset` still names the block it was handed out for."""
        base = offset - CHUNK_HEADER_SIZE
        if base < 0 or offset > len(self.map):
            return False
        if struct.unpack_from("<I", self.map, base + CHUNK_MAGIC_OFF)[0] != CHUNK_MAGIC:
            return False
        live = struct.unpack_from("<I", self.map, base + CHUNK_GENERATION_OFF)[0]
        flags = struct.unpack_from("<H", self.map, base + CHUNK_FLAGS_OFF)[0]
        return live == generation and (flags & CHUNK_FREE) == 0

    def attach(self, offset, generation, dtype, shape):
        """Wraps a block the engine has already filled, for reading."""
        if isinstance(dtype, int):
            dtype = _DTYPE_TABLE[dtype][0]
        nbytes = _itemsize(dtype)
        for extent in shape:
            nbytes *= extent
        if not self.handle_is_live(offset, generation):
            raise ShmError(f"block at offset {offset} is no longer generation {generation}")
        return Block(self, offset, generation, nbytes, dtype, shape, self._release)

    def allocate(self, dtype, shape):
        """Asks Java for a block and hands it back writable, for sending data out."""
        if self._broker is None:
            raise ShmError("no channel to the Java side: this kernel cannot allocate")
        if isinstance(dtype, int):
            dtype = _DTYPE_TABLE[dtype][0]
        if dtype not in _DTYPE_CODES:
            raise ShmError(f"unknown dtype {dtype!r}")
        nbytes = _itemsize(dtype)
        for extent in shape:
            nbytes *= extent
        offset, generation = self._broker.allocate(nbytes, _DTYPE_CODES[dtype])
        if offset == 0:
            raise ShmError(f"the engine refused a block of {nbytes} bytes")
        return Block(self, offset, generation, nbytes, dtype, shape, self._release)

    def _release(self, offset, generation):
        if self._broker is not None:
            self._broker.release(offset, generation)


def _itemsize(dtype):
    for name, size in _DTYPE_TABLE.values():
        if name == dtype:
            return size
    raise ShmError(f"unknown dtype {dtype!r}")


# ---------------------------------------------------------------------------
# The channel to Java, over the kernel's own line protocol
# ---------------------------------------------------------------------------

class KernelBroker:
    """Asks the Java side to allocate and free, over the stdio line protocol.

    Java owns the allocator, so the CAS that claims a block happens in exactly one
    place. Only the request travels; the data never leaves the shared region.
    """

    def __init__(self, send, wait_for):
        self._send = send
        self._wait_for = wait_for
        self._next_id = 0

    def _request(self, message):
        self._next_id += 1
        message["rid"] = self._next_id
        self._send(message)
        return self._wait_for(self._next_id)

    def allocate(self, nbytes, dtype_code):
        reply = self._request({"t": "shm_alloc", "bytes": nbytes, "dtype": dtype_code})
        return int(reply.get("offset", 0)), int(reply.get("generation", 0))

    def release(self, offset, generation):
        self._send({"t": "shm_release", "offset": offset, "generation": generation})


_REGION = None


def region():
    """The region this kernel is attached to, opened on first use."""
    global _REGION
    if _REGION is None:
        path = os.environ.get("SPHERE_SHM_PATH")
        if not path:
            raise ShmError("SPHERE_SHM_PATH is not set: Sphere did not attach this kernel")
        _REGION = Region(path, broker=_default_broker())
    return _REGION


_BROKER_FACTORY = None


def set_broker_factory(factory):
    """Installed by the kernel driver, which owns the line protocol."""
    global _BROKER_FACTORY
    _BROKER_FACTORY = factory


def _default_broker():
    return _BROKER_FACTORY() if _BROKER_FACTORY is not None else None


def attach(offset, generation, dtype, shape):
    return region().attach(offset, generation, dtype, shape)


def allocate(dtype, shape):
    return region().allocate(dtype, shape)
