name: Build All Sphere Executables

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            run_cmd: cmd /c build_windows.bat
            artifact: Sphere-Windows-v2026.1.0
          - os: ubuntu-latest
            run_cmd: chmod +x build_linux.sh && ./build_linux.sh
            artifact: Sphere-Linux-v2026.1.0
          - os: macos-latest
            run_cmd: chmod +x build_macos.sh && ./build_macos.sh
            artifact: Sphere-macOS-v2026.1.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 26
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '26'

      - name: Build Executable
        run: ${{ matrix.run_cmd }}

      - name: Upload Finished Executable (.zip)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/